Add check_services() and only create lemonbar/termbar in case the specified services (as of now only mpd(1)). Otherwise abort with exit 1.

diff --git a/barstarter b/barstarter
--- a/barstarter
+++ b/barstarter
@@ -11,6 +11,10 @@ autoselect() {
 	fi
 }
 
+check_services() {
+	pgrep -q mpd || echo "mpd is not running. Aborting." && exit 1
+}
+
 clean_up_bars() {
 	pgrep -fq termbar && kill -9 $(pgrep -f termbar)
 	pgrep -q lemonbar && pkill lemonbar
@@ -66,10 +70,12 @@ h)
 	;;
 l)
 	clean_up_bars
+	check_services
 	make_lemonbar
 	;;
 t)
 	clean_up_bars
+	check_services
 	make_termbar
 	;;
 x)
@@ -78,5 +84,6 @@ x)
 	;;
 *)
 	clean_up_bars
+	check_services
 	autoselect
 esac
